/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiConfigForm: typeof import('./src/components/ai-config/AiConfigForm.vue')['default']
    AiConfigList: typeof import('./src/components/ai-config/AiConfigList.vue')['default']
    AiConfigModal: typeof import('./src/components/ai-config/AiConfigModal.vue')['default']
    ChatHistory: typeof import('./src/components/interview/ChatHistory.vue')['default']
    ChatInput: typeof import('./src/components/interview/ChatInput.vue')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellCommand: typeof import('./src/components/ShellCommand.vue')['default']
    SiteConfigEditor: typeof import('./src/components/SiteConfigEditor.vue')['default']
  }
}
